### ISSUE TITLE
Fix .steam

### ISSUE THREAD

**Issue by FM1337** [Liamraystanley/Code#102]
Yesh yesh yesh I know .steam is broken due to either cloudflare or steamdb as you said, but I also believe you said you'd use a different method to fetch information.

So pls fix it.

-FMCore (Aka FM1337, Aka Allen`)

**Comment by FM1337** [comment]
And yes I also know you added a can't fix tag to the other one, but there are steam apis you can use.

**Comment by lukeroge** [comment]
I managed to solve this on my bot using cfscape, a module that scrapes
cloudflare sites. It's a rather big module, though.
