### ISSUE TITLE
.lastfm broken due to site change.

### ISSUE THREAD

**Issue by FM1337** [Liamraystanley/Code#107]
Due to lastfm changing their site layout and functioning recently, it has broken the .lastfm module resulting in this error.

AttributeError: 'bool' object has no attribute 'text' (file "/root/Code/modules/lastfm.py", line 22, in lastfm)

**Comment by Liamraystanley** [comment]
Looking over this, it looks as though with last.fm's recent site changes, they've taken down their API's. From the sounds of it these should be back up and running once the site changes have finished. I'll keep this issue open.

**Comment by Liamraystanley** [comment]
This should be resolved as of commit a36f49ad453613d44fef98ad1274767baf04a834
