### ISSUE TITLE
Reloading config.json without restarting bot

### ISSUE THREAD

**Issue by Aareon** [Liamraystanley/Code#111]
Thank you for your continued support,

I'm wondering how I would go about reloading the config.json without completely restarting my bot.
Thank you again,
Aareon

**Comment by Liamraystanley** [comment]
Hello,

What types of options are you looking to reload? By default, any modules which have configuration options in the config file can be reloaded with **.reload**. There is also **.restart**, which reads a few additional options once again, from the config.

At this time, the way that the config is setup, there is no way to refresh the bot with what is in the config, other than what is mentioned above.

**Comment by Aareon** [comment]
Answered. Thank you.
