### ISSUE TITLE
Code is not defined outside of function

### ISSUE THREAD

**Issue by Aareon** [Liamraystanley/Code#112]
Sorry to continually bother you,
I need to use Code outside of a function and can't `func(code, variable)` if where I'm coming from in my script doesn't have code defined in it. Any solutions?

Thanks again,
Aareon

**Comment by Liamraystanley** [comment]
Hello,

You're more than happy to continue to ask questions. In this instance, the way modules and module hooks are invoked, the simplest way is to use a setup function, and a global variable.

For example, here is a small module, that allows you to take code, and make it a global variable, allowing you to access that variable from outside of a modularized function:

```python
from util.hook import *

bot = None

def setup(code):
    # When the module is loaded, Code will search for any setup functions,
    # and pass along itself as a param and execute the function. So, we can
    # load in the global bot variable for editing
    global bot
    # And set our global variable to code
    bot = code

def some_other_function():
    # This function now has access to our code class object
    # Ensure that you use bot, rather than code, when accessing the
    # variable
    print(bot.nick)

@hook(cmds=['example'])
def example_func(code, input):
    """ This is an example function. """
    code.reply("Hello world!")
```

I hope this answers your questions.

**Comment by Aareon** [comment]
Answered. Thank you.
